services:
  kafka: 
    image: apache/kafka:4.0.0 # image Docker de Kafka pour reproductibilité et portabilité du pipeline 
    container_name: kafka  
    hostname: kafka # adresse réseau par laquelle les autres containers communiquent avec Kafka 
    ports:
      - "9092:9092" 
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  producer:
    build: ./producer # construction de l'image Docker à partir du Dockerfile
    depends_on:
      - kafka # s'assure que Kafka démarre avant le producer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092 # adresse IP par laquelle le producer accède à Kafka
    restart: on-failure # redémarre automatiquement le producer en cas d'erreur

  spark:
    build: ./spark
    depends_on:
      - kafka
    environment:
      - SPARK_LOCAL_IP=spark
      - SPARK_USER=root
    restart: on-failure

  opensearch: # Moteur de recherche et d'analyse de données
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch 
    hostname: opensearch # adresse réseau par laquelle les autres containers communiquent avec OpenSearch 
    environment:
      - discovery.type=single-node # tourne seul, pas en cluster
      - DISABLE_SECURITY_PLUGIN=true # désactive le plugin de sécurité pour simplifier l'authentification
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # alloue 512 Mo de RAM à OpenSearch (sinon prend 50% de la RAM)
    ports:
      - "9200:9200" # expose le port 9200 pour accéder à OpenSearch

  opensearch-dashboards: # Interface graphique pour visualiser les données d'OpenSearch
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    depends_on:
      - opensearch
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200 # adresse IP par laquelle OpenSearch Dashboards accède à OpenSearch 
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true 
    ports:
      - "5601:5601" # expose le port 5601 pour accéder à OpenSearch Dashboards via localhost:5601